baseURL = "https://ally.id/"
languageCode = "en-us"
title = "ally"
theme= "ally"
paginatePath = ""

[permalinks]
  news = "/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
